#!/bin/sh

set -e

URL="github.com/toothris"
WIDTH=800
HEIGHT=600
START_LEN=100
START_SIZE=80
FPS=60
DISPLAY=:1

xmp -d wav -o music.wav res/artificial_sweetener.xm

FRAME=0
while [ $FRAME -lt $START_LEN ] ; do
  if [[ $((FRAME % 10)) -eq 0 ]] ; then echo "start frame $FRAME" ; fi
  SCALE=$(bc <<< "scale=2; $START_SIZE+((100-$START_SIZE)*$FRAME/$START_LEN)")
  convert \
    '(' -background black -fill white -gravity center \
        -font /usr/share/fonts/TTF/DejaVuSansMono.ttf \
        -pointsize 90 label:"$URL" \
        -resize ${WIDTH}x${HEIGHT} \
    ')' \
    -scale $SCALE% \
    -extent ${WIDTH}x${HEIGHT} \
    $(printf 'start%06d.bmp' $FRAME)
  ((FRAME += 1))
done

Xvfb $DISPLAY -screen 0 ${WIDTH}x${HEIGHT}x24 &
XVFB=$!

set +e
python2 -B toothris.py --width $WIDTH --height $HEIGHT --fps $FPS \
  --freefps --replay --events event_logs/demo.events --frames 'game%06d.bmp' \
  --stopframe 200
set -e

kill $XVFB
